### PR TITLE
Added Event model and updates Active record relationships

### PR DESCRIPTION
**Pull request by HarshwardhanSingh**

### CODE REVIEW

**Comment by revathskumar** [comment]
@HarshwardhanSingh As discussed in demo you can rename the table to leaves instead of events.

**Comment by HarshwardhanSingh** [comment]
Then we would need to rename the events_controllers to leave_controllers as well.

**Comment by revathskumar** [comment]
yes. But there is no leaves controller as of now. Do they?

**Comment by revathskumar** [comment]
Ya in the other PR it has. okey. once we merge those we will rename it.

**Comment by HarshwardhanSingh** [comment]
Closing the PR for creating new one for leave model.

**Pull request closed without merging**
